var str=new String("Shashank is in Berkedia");
console.log(str);
console.log(str.length);
console.log(str.indexOf("Berkedia"));
console.log(str.search("Berkedia"));
console.log(str.slice(0,8));
console.log(str.substr(9));
console.log(str.replace("Shashank","Ganesh"));
console.log(str.toUpperCase());
console.log(str.toLowerCase());
console.log(str.concat(" ","with"," ","Ganesh"));
console.log(str.charAt(0));
console.log(str.split(" "));